steps:
- uses: Jimver/cuda-toolkit@v0.2.2
  id: cuda-toolkit
  with:
    cuda: '11.2.2'

- name: Show CUDA version
  run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

- name: CUDA install location
  run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

- mame: test nvcc command
  run: nvcc -V

- name: show cmake version
  run: cmake --version
