name: action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cuda_versions: ['10.2.89', '11.2.1', '11.2.2', '11.3.1']
    steps:
    - uses: Jimver/cuda-toolkit@v0.2.2
      id: cuda-toolkit
      with:
        cuda: ${{ matrix.cuda_versions }}
    - name: test nvcc command
      run: nvcc -V
    - name: show cmake version
      run: cmake --version
    - name: test build
      run: |
        git clone https://github.com/utcs-scea/altis.git
        cd altis/tools
        chmod +x github-action-setup.sh
        ./github-action-setup.sh