name: action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Jimver/cuda-toolkit@v0.2.2
      id: cuda-toolkit
      with:
        cuda: '11.2.2'
    - name: test nvcc command
      run: nvcc -V
    - name: show cmake version
      run: cmake --version
    - name: prepare
      run: |
        echo "${GITHUB_WORKSPACE}"
        pwd
        ls -a ${GITHUB_WORKSPACE}
        ls -a ${GITHUB_WORKSPACE}/..
        chmod +x "${GITHUB_WORKSPACE}/.github./github-action-setup.sh"
    - name: Altis test build
      run: ${GITHUB_WORKSPACE}/.github./github-action-setup.sh
