steps:
- uses: Jimver/cuda-toolkit@v0.2.2
  id: cuda-toolkit
  with:
    cuda: '11.2.2'

- run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"

- run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

- run: nvcc -V

- run: cmake --version
